import { Footer } from "@/components/footer";
import "./globals.css";
import { Inter } from "next/font/google";
import icon from "./favicon.ico";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "RiDA",
  description: "Generated by create next app",
  icon: { icon },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className={inter.className}>
        <div className="min-h-screen">{children}</div>
      </body>
    </html>
  );
}
